import Head from 'next/head'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {useDispatch, useSelector} from "react-redux";
import {
    selectAuthState,
    selectUserAddress,
    setAuthState,
    setChainId,
    setUserAddress
} from "@/redux/store/authSlice";
import Header from "@/components/Header/Header";
import {useEffect} from "react";
import {checkIsWalletConnected} from "@/helpers/checkIsWalletConnected";
import {getUserBalance} from "@/helpers/getUserBalance";
import {setUserBalance} from "@/redux/store/userDataSlice";

const inter = Inter({subsets: ['latin']})


const Home = () => {
    const authState = useSelector(selectAuthState)
    const userAddress = useSelector(selectUserAddress)
    const dispatch = useDispatch()

    const dispatchAuthState = (result) => dispatch(setAuthState(result))
    const dispatchUserAddress = (result) => dispatch(setUserAddress(result))
    const dispatchChainId = (result) => dispatch(setChainId(result))
    const dispatchUserBalance = (result) => dispatch(setUserBalance(result))

    useEffect(() => {
        checkIsWalletConnected(dispatchAuthState, dispatchUserAddress, dispatchChainId)
    }, [])

    useEffect(() => {
        getUserBalance(userAddress, dispatchUserBalance)
    }, [userAddress])

    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <Header/>
                <div className={styles.description}>
                    <h1>authState: {authState.toString()}</h1>
                </div>
            </main>
        </>
    )
}
export default Home
